<Project Sdk="MSTest.Sdk/4.1.0">
  <PropertyGroup>
    <RootNamespace>Tellurian.Trains.ClockPulseApp.Service.Tests</RootNamespace>
    <AssemblyName>Tellurian.Trains.ClockPulseApp.Service.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Service\Service.csproj" />
  </ItemGroup>
</Project>
